In [21]:
import pandas as pd

df = pd.read_csv('../data/wpg_ghsom_small_tau2/rnn_input_cluster_integer.csv')

5

69900

In [41]:
input_file_path = '../data/wpg_ghsom_small_tau2/seqGAN_input_data.txt'
df = pd.read_csv(input_file_path,  sep=' ',header=None)
df.max()

0     55600
1     32200
2     55600
3     55399
4     32200
5     57299
6     58200
7     58200
8     58399
9     32100
10    58399
11    57299
12    58399
13    58200
14    36200
15    36200
16    57299
17    57600
18    58500
19    57299
20    58500
21    57440
22    58399
23    58200
24    58500
25    58399
26    58500
27    57600
28    57450
29    38700
      ...
66    64500
67    68600
68    66400
69    68600
70    69300
71    44900
72    67100
73    69300
74    69700
75    64500
76    69900
77    69800
78    64300
79    68600
80    69500
81    64300
82    68600
83    69700
84    64300
85    69800
86    69800
87    64099
88    64300
89    69800
90    69900
91    64300
92    69800
93    69900
94    69800
95    69900
Length: 96, dtype: int64

In [45]:
max_values_of_columns = df.max()
print('max cluster:',max_values_of_columns)
vocab_size = max(max_values_of_columns[0:int(df.shape[1])])
print(vocab_size)

max cluster: 0     55600
1     32200
2     55600
3     55399
4     32200
5     57299
6     58200
7     58200
8     58399
9     32100
10    58399
11    57299
12    58399
13    58200
14    36200
15    36200
16    57299
17    57600
18    58500
19    57299
20    58500
21    57440
22    58399
23    58200
24    58500
25    58399
26    58500
27    57600
28    57450
29    38700
      ...
66    64500
67    68600
68    66400
69    68600
70    69300
71    44900
72    67100
73    69300
74    69700
75    64500
76    69900
77    69800
78    64300
79    68600
80    69500
81    64300
82    68600
83    69700
84    64300
85    69800
86    69800
87    64099
88    64300
89    69800
90    69900
91    64300
92    69800
93    69900
94    69800
95    69900
Length: 96, dtype: int64
69900

In [34]:
a = 2569565
def getClusterList(cluster):
    cluster_list = []
    while(True):
        if cluster < 10:
            cluster_list.append(cluster)
            break
        else:
            value = cluster%10
            cluster_list.append(int(value))
            if(cluster>1):
                cluster = int(cluster/10)
            else:
                break
    cluster_list.reverse()
    return cluster_list

getClusterList(a)

[2, 5, 6, 9, 5, 6, 5]

In [41]:
import pandas as pd
import numpy as np

# raw data
#df = pd.read_csv('item_seqGAN_0608.csv')
# df = pd.read_csv('../data/wpg_ghsom_small/rnn_input_cluster_integer.csv')
df = pd.read_csv('../data/simliar_rnn_output.csv')
df_split = df.iloc[:,91:96]
df_split.columns=range(0,5)
# df_split = df_split.iloc[1:3,:]
# df_split = [[0,0,158,241,0],[0,125,0,210,0]]

df_split = pd.DataFrame(df_split)
df_split
df_split

   0  1  2  3  4
0  0  0  0  0  0
1  0  0  0  0  0
2  0  0  0  0  0
3  0  0  0  0  0
4  0  0  0  0  0
5  0  0  0  0  0
6  0  0  0  0  0
7  0  0  0  0  0
8  0  0  0  0  0
9  0  0  0  0  0

In [42]:
# seqGAN data
# df_seqGAN = pd.read_csv('../data/wpg_ghsom_small/seqGAN_output_sequence.txt',sep=' ',header=None)
df_seqGAN = pd.read_csv('../data/seqGAN_sequence.txt',sep=' ',header=None)
df_seqGAN_split = df_seqGAN.iloc[:,91:96]
df_seqGAN_split.columns=range(0,5)
df_seqGAN_split
# df_seqGAN_split = df_seqGAN_split.iloc[1:3,:]
df_seqGAN_split

# df_seqGAN_split = [[0,0,117,851,0],[600,128,811,0,0]]

df_seqGAN_split = pd.DataFrame(df_seqGAN_split)
df_seqGAN_split

     0    1    2    3    4
0  231  221  120  225  320
1  236  236  236  236  221
2  550  211  231    0  180
3  231    0  231    0  234
4  440    0    0  440  460
5  110  217  217    0    0
6  235  231  235    0  235
7  420  231    0  231  234
8  234    0    0    0  231
9  231  231  236  231  231

In [43]:
# max_value = max(df_seqGAN_split.max()[0:96])
max_value = max(df_seqGAN_split.max())
layer = 0
days = 5
print('max_value:',max_value)
while(True):
    if(max_value>1):
        max_value = max_value/10
        layer = layer+1
    else:
        break
print('Layer:',layer)

number_ditgit = [1,2].reverse()
layer = 0
# All layer 
days_list = np.zeros((len(number_ditgits), 5)) # 取代 count92,93,94,95,96
for layer_value in range(len(number_ditgits)):
    layer = number_ditgits[layer_value] + v
    for i in range(int(df_seqGAN_split.shape[0])):
        
        for day in range(days_list.shape[1]):
            print('i=',i)
            print('layer_value=',layer_value,'\t day=',day)
            print(df_split.iloc[i][day]//pow(10,layer_value),'-',df_seqGAN_split.iloc[i][day]//pow(10,layer_value),'=',df_split.iloc[i][day]//pow(10,layer_value)-df_seqGAN_split.iloc[i][day]//pow(10,layer_value))
            if (df_split.iloc[i][day]//pow(10,layer_value)-df_seqGAN_split.iloc[i][day]//pow(10,layer_value))==0:
                days_list[layer_value][day] = days_list[layer_value][day] + 1
        print(days_list)
#             p_array.append(days_list[layer_value][day])
#     print("p average :", np.average(p_array))

max_value: 550
Layer: 3
i= 0
layer_value= 0 	 day= 0
0 - 231 = -231
i= 0
layer_value= 0 	 day= 1
0 - 221 = -221
i= 0
layer_value= 0 	 day= 2
0 - 120 = -120
i= 0
layer_value= 0 	 day= 3
0 - 225 = -225
i= 0
layer_value= 0 	 day= 4
0 - 320 = -320
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
i= 1
layer_value= 0 	 day= 0
0 - 236 = -236
i= 1
layer_value= 0 	 day= 1
0 - 236 = -236
i= 1
layer_value= 0 	 day= 2
0 - 236 = -236
i= 1
layer_value= 0 	 day= 3
0 - 236 = -236
i= 1
layer_value= 0 	 day= 4
0 - 221 = -221
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
i= 2
layer_value= 0 	 day= 0
0 - 550 = -550
i= 2
layer_value= 0 	 day= 1
0 - 211 = -211
i= 2
layer_value= 0 	 day= 2
0 - 231 = -231
i= 2
layer_value= 0 	 day= 3
0 - 0 = 0
i= 2
layer_value= 0 	 day= 4
0 - 180 = -180
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
i= 3
layer_value= 0 	 day= 0
0 - 231 = -231
i= 3
layer_value= 0 	 day= 1
0 - 0 = 0
i= 3
layer_value= 0 	 day= 2
0 - 231 = -231
i= 3
layer_value= 0 	 day= 3
0 - 0 = 0
i= 3
layer_value= 0 	 day= 4
0 - 234 = -234
[[0. 1. 0. 2. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
i= 4
layer_value= 0 	 day= 0
0 - 440 = -440
i= 4
layer_value= 0 	 day= 1
0 - 0 = 0
i= 4
layer_value= 0 	 day= 2
0 - 0 = 0
i= 4
layer_value= 0 	 day= 3
0 - 440 = -440
i= 4
layer_value= 0 	 day= 4
0 - 460 = -460
[[0. 2. 1. 2. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
i= 5
layer_value= 0 	 day= 0
0 - 110 = -110
i= 5
layer_value= 0 	 day= 1
0 - 217 = -217
i= 5
layer_value= 0 	 day= 2
0 - 217 = -217
i= 5
layer_value= 0 	 day= 3
0 - 0 = 0
i= 5
layer_value= 0 	 day= 4
0 - 0 = 0
[[0. 2. 1. 3. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
i= 6
layer_value= 0 	 day= 0
0 - 235 = -235
i= 6
layer_value= 0 	 day= 1
0 - 231 = -231
i= 6
layer_value= 0 	 day= 2
0 - 235 = -235
i= 6
layer_value= 0 	 day= 3
0 - 0 = 0
i= 6
layer_value= 0 	 day= 4
0 - 235 = -235
[[0. 2. 1. 4. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
i= 7
layer_value= 0 	 day= 0
0 - 420 = -420
i= 7
layer_value= 0 	 day= 1
0 - 231 = -231
i= 7
layer_value= 0 	 day= 2
0 - 0 = 0
i= 7
layer_value= 0 	 day= 3
0 - 231 = -231
i= 7
layer_value= 0 	 day= 4
0 - 234 = -234
[[0. 2. 2. 4. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
i= 8
layer_value= 0 	 day= 0
0 - 234 = -234
i= 8
layer_value= 0 	 day= 1
0 - 0 = 0
i= 8
layer_value= 0 	 day= 2
0 - 0 = 0
i= 8
layer_value= 0 	 day= 3
0 - 0 = 0
i= 8
layer_value= 0 	 day= 4
0 - 231 = -231
[[0. 3. 3. 5. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
i= 9
layer_value= 0 	 day= 0
0 - 231 = -231
i= 9
layer_value= 0 	 day= 1
0 - 231 = -231
i= 9
layer_value= 0 	 day= 2
0 - 236 = -236
i= 9
layer_value= 0 	 day= 3
0 - 231 = -231
i= 9
layer_value= 0 	 day= 4
0 - 231 = -231
[[0. 3. 3. 5. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
i= 0
layer_value= 1 	 day= 0
0 - 23 = -23
i= 0
layer_value= 1 	 day= 1
0 - 22 = -22
i= 0
layer_value= 1 	 day= 2
0 - 12 = -12
i= 0
layer_value= 1 	 day= 3
0 - 22 = -22
i= 0
layer_value= 1 	 day= 4
0 - 32 = -32
[[0. 3. 3. 5. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
i= 1
layer_value= 1 	 day= 0
0 - 23 = -23
i= 1
layer_value= 1 	 day= 1
0 - 23 = -23
i= 1
layer_value= 1 	 day= 2
0 - 23 = -23
i= 1
layer_value= 1 	 day= 3
0 - 23 = -23
i= 1
layer_value= 1 	 day= 4
0 - 22 = -22
[[0. 3. 3. 5. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
i= 2
layer_value= 1 	 day= 0
0 - 55 = -55
i= 2
layer_value= 1 	 day= 1
0 - 21 = -21
i= 2
layer_value= 1 	 day= 2
0 - 23 = -23
i= 2
layer_value= 1 	 day= 3
0 - 0 = 0
i= 2
layer_value= 1 	 day= 4
0 - 18 = -18
[[0. 3. 3. 5. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]
i= 3
layer_value= 1 	 day= 0
0 - 23 = -23
i= 3
layer_value= 1 	 day= 1
0 - 0 = 0
i= 3
layer_value= 1 	 day= 2
0 - 23 = -23
i= 3
layer_value= 1 	 day= 3
0 - 0 = 0
i= 3
layer_value= 1 	 day= 4
0 - 23 = -23
[[0. 3. 3. 5. 1.]
 [0. 1. 0. 2. 0.]
 [0. 0. 0. 0. 0.]]
i= 4
layer_value= 1 	 day= 0
0 - 44 = -44
i= 4
layer_value= 1 	 day= 1
0 - 0 = 0
i= 4
layer_value= 1 	 day= 2
0 - 0 = 0
i= 4
layer_value= 1 	 day= 3
0 - 44 = -44
i= 4
layer_value= 1 	 day= 4
0 - 46 = -46
[[0. 3. 3. 5. 1.]
 [0. 2. 1. 2. 0.]
 [0. 0. 0. 0. 0.]]
i= 5
layer_value= 1 	 day= 0
0 - 11 = -11
i= 5
layer_value= 1 	 day= 1
0 - 21 = -21
i= 5
layer_value= 1 	 day= 2
0 - 21 = -21
i= 5
layer_value= 1 	 day= 3
0 - 0 = 0
i= 5
layer_value= 1 	 day= 4
0 - 0 = 0
[[0. 3. 3. 5. 1.]
 [0. 2. 1. 3. 1.]
 [0. 0. 0. 0. 0.]]
i= 6
layer_value= 1 	 day= 0
0 - 23 = -23
i= 6
layer_value= 1 	 day= 1
0 - 23 = -23
i= 6
layer_value= 1 	 day= 2
0 - 23 = -23
i= 6
layer_value= 1 	 day= 3
0 - 0 = 0
i= 6
layer_value= 1 	 day= 4
0 - 23 = -23
[[0. 3. 3. 5. 1.]
 [0. 2. 1. 4. 1.]
 [0. 0. 0. 0. 0.]]
i= 7
layer_value= 1 	 day= 0
0 - 42 = -42
i= 7
layer_value= 1 	 day= 1
0 - 23 = -23
i= 7
layer_value= 1 	 day= 2
0 - 0 = 0
i= 7
layer_value= 1 	 day= 3
0 - 23 = -23
i= 7
layer_value= 1 	 day= 4
0 - 23 = -23
[[0. 3. 3. 5. 1.]
 [0. 2. 2. 4. 1.]
 [0. 0. 0. 0. 0.]]
i= 8
layer_value= 1 	 day= 0
0 - 23 = -23
i= 8
layer_value= 1 	 day= 1
0 - 0 = 0
i= 8
layer_value= 1 	 day= 2
0 - 0 = 0
i= 8
layer_value= 1 	 day= 3
0 - 0 = 0
i= 8
layer_value= 1 	 day= 4
0 - 23 = -23
[[0. 3. 3. 5. 1.]
 [0. 3. 3. 5. 1.]
 [0. 0. 0. 0. 0.]]
i= 9
layer_value= 1 	 day= 0
0 - 23 = -23
i= 9
layer_value= 1 	 day= 1
0 - 23 = -23
i= 9
layer_value= 1 	 day= 2
0 - 23 = -23
i= 9
layer_value= 1 	 day= 3
0 - 23 = -23
i= 9
layer_value= 1 	 day= 4
0 - 23 = -23
[[0. 3. 3. 5. 1.]
 [0. 3. 3. 5. 1.]
 [0. 0. 0. 0. 0.]]
i= 0
layer_value= 2 	 day= 0
0 - 2 = -2
i= 0
layer_value= 2 	 day= 1
0 - 2 = -2
i= 0
layer_value= 2 	 day= 2
0 - 1 = -1
i= 0
layer_value= 2 	 day= 3
0 - 2 = -2
i= 0
layer_value= 2 	 day= 4
0 - 3 = -3
[[0. 3. 3. 5. 1.]
 [0. 3. 3. 5. 1.]
 [0. 0. 0. 0. 0.]]
i= 1
layer_value= 2 	 day= 0
0 - 2 = -2
i= 1
layer_value= 2 	 day= 1
0 - 2 = -2
i= 1
layer_value= 2 	 day= 2
0 - 2 = -2
i= 1
layer_value= 2 	 day= 3
0 - 2 = -2
i= 1
layer_value= 2 	 day= 4
0 - 2 = -2
[[0. 3. 3. 5. 1.]
 [0. 3. 3. 5. 1.]
 [0. 0. 0. 0. 0.]]
i= 2
layer_value= 2 	 day= 0
0 - 5 = -5
i= 2
layer_value= 2 	 day= 1
0 - 2 = -2
i= 2
layer_value= 2 	 day= 2
0 - 2 = -2
i= 2
layer_value= 2 	 day= 3
0 - 0 = 0
i= 2
layer_value= 2 	 day= 4
0 - 1 = -1
[[0. 3. 3. 5. 1.]
 [0. 3. 3. 5. 1.]
 [0. 0. 0. 1. 0.]]
i= 3
layer_value= 2 	 day= 0
0 - 2 = -2
i= 3
layer_value= 2 	 day= 1
0 - 0 = 0
i= 3
layer_value= 2 	 day= 2
0 - 2 = -2
i= 3
layer_value= 2 	 day= 3
0 - 0 = 0
i= 3
layer_value= 2 	 day= 4
0 - 2 = -2
[[0. 3. 3. 5. 1.]
 [0. 3. 3. 5. 1.]
 [0. 1. 0. 2. 0.]]
i= 4
layer_value= 2 	 day= 0
0 - 4 = -4
i= 4
layer_value= 2 	 day= 1
0 - 0 = 0
i= 4
layer_value= 2 	 day= 2
0 - 0 = 0
i= 4
layer_value= 2 	 day= 3
0 - 4 = -4
i= 4
layer_value= 2 	 day= 4
0 - 4 = -4
[[0. 3. 3. 5. 1.]
 [0. 3. 3. 5. 1.]
 [0. 2. 1. 2. 0.]]
i= 5
layer_value= 2 	 day= 0
0 - 1 = -1
i= 5
layer_value= 2 	 day= 1
0 - 2 = -2
i= 5
layer_value= 2 	 day= 2
0 - 2 = -2
i= 5
layer_value= 2 	 day= 3
0 - 0 = 0
i= 5
layer_value= 2 	 day= 4
0 - 0 = 0
[[0. 3. 3. 5. 1.]
 [0. 3. 3. 5. 1.]
 [0. 2. 1. 3. 1.]]
i= 6
layer_value= 2 	 day= 0
0 - 2 = -2
i= 6
layer_value= 2 	 day= 1
0 - 2 = -2
i= 6
layer_value= 2 	 day= 2
0 - 2 = -2
i= 6
layer_value= 2 	 day= 3
0 - 0 = 0
i= 6
layer_value= 2 	 day= 4
0 - 2 = -2
[[0. 3. 3. 5. 1.]
 [0. 3. 3. 5. 1.]
 [0. 2. 1. 4. 1.]]
i= 7
layer_value= 2 	 day= 0
0 - 4 = -4
i= 7
layer_value= 2 	 day= 1
0 - 2 = -2
i= 7
layer_value= 2 	 day= 2
0 - 0 = 0
i= 7
layer_value= 2 	 day= 3
0 - 2 = -2
i= 7
layer_value= 2 	 day= 4
0 - 2 = -2
[[0. 3. 3. 5. 1.]
 [0. 3. 3. 5. 1.]
 [0. 2. 2. 4. 1.]]
i= 8
layer_value= 2 	 day= 0
0 - 2 = -2
i= 8
layer_value= 2 	 day= 1
0 - 0 = 0
i= 8
layer_value= 2 	 day= 2
0 - 0 = 0
i= 8
layer_value= 2 	 day= 3
0 - 0 = 0
i= 8
layer_value= 2 	 day= 4
0 - 2 = -2
[[0. 3. 3. 5. 1.]
 [0. 3. 3. 5. 1.]
 [0. 3. 3. 5. 1.]]
i= 9
layer_value= 2 	 day= 0
0 - 2 = -2
i= 9
layer_value= 2 	 day= 1
0 - 2 = -2
i= 9
layer_value= 2 	 day= 2
0 - 2 = -2
i= 9
layer_value= 2 	 day= 3
0 - 2 = -2
i= 9
layer_value= 2 	 day= 4
0 - 2 = -2
[[0. 3. 3. 5. 1.]
 [0. 3. 3. 5. 1.]
 [0. 3. 3. 5. 1.]]

In [44]:
df_layer = pd.DataFrame(days_list/df_seqGAN_split.shape[0])
df_layer

     0    1    2    3    4
0  0.0  0.3  0.3  0.5  0.1
1  0.0  0.3  0.3  0.5  0.1
2  0.0  0.3  0.3  0.5  0.1

In [45]:
df_layer = pd.DataFrame(days_list/df_seqGAN_split.shape[0])
layer_name = []
for i in range(layer,0,-1):
    print(i)
    layer_display = list(range(i, 0,-1))
    layer_name.append('Layer %s '% layer_display)
    
print(layer_name)    
df_layer['layer'] = layer_name
df_layer

3
2
1
['Layer [3, 2, 1] ', 'Layer [2, 1] ', 'Layer [1] ']

     0    1    2    3    4             layer
0  0.0  0.3  0.3  0.5  0.1  Layer [3, 2, 1]
1  0.0  0.3  0.3  0.5  0.1     Layer [2, 1]
2  0.0  0.3  0.3  0.5  0.1        Layer [1]